language: generic
dist: xenial

arch:
- ppc64le
- s390x
- arm64
- amd64

services:
- redis
- mysql
- rabbitmq
- mongodb
- postgresql

script:
- ps auxf
- php -v
- java -version
- python -V
- psql -V
- postgres -V
