language: generic
dist: bionic

arch:
- ppc64le
- s390x
- arm64
- amd64

services:
- redis
- mysql
- rabbitmq
- mongodb
- postgresql

script:
- ps auxfww
- php -v
- java -version
- python -V
- psql -V
- postgres -V
